# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 'Install dependencies'
        run: rm -rf node_modules && pnpm install --frozen-lockfile
      # - run: pnpm run build --if-present
      - name: SSH Remote Commands
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@f9010ff7f1bbd7db1a0b4bab661437550cea20c0
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST_IP }}
          port: ${{ secrets.HOST_PORT }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_SSH_KEY }}
          script: |
            pm2 delete all
            cd /root/YEEH1
            git pull
            pnpm install
            pm2 start src/index.js
